const crypto = require('crypto');
const User = require('../app/models/User'); // Ensure the path to User model is correct

// Function to generate a random token and validate its uniqueness
const autoGeneratedToken = async () => {
  const length = 10;
  const charset = 'ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789';
  let tokenExists = true;
  token = '';
  for (let i = 0; i < length; i++) {
    const randomIndex = crypto.randomInt(0, charset.length);
    token += charset[randomIndex];
  }

  return token; // Return the valid, unique token
}

module.exports = autoGeneratedToken;
